# Change these first
owner: glefait # Your GitHub organization or username, where this repository lives
repo: martinique-public-websites # The name of this repository

sites:
  - name: CTM
    url: https://www.collectivitedemartinique.mq
  - name: CACEM
    url: https://www.cacem.fr
  - name: Espace Sud
    url: http://espacesud.fr
  - name: Cap Nord
    url: http://www.capnordmartinique.fr
  - name: Fort-de-France
    url: https://www.fortdefrance.fr
  - name: Schoelcher
    url: https://www.mairie-schoelcher.fr
  - name: Saint-Joseph
    url: https://saintjoseph972.com
  - name: Le Lamentin
    url: http://www.mairie-lelamentin.fr
  - name: Sainte-Luce
    url: https://www.sainteluce.fr
  - name: La Trinite
    url: https://www.mairie-latrinite.fr
  - name: Le Vauclin
    url: http://ville-vauclin.fr
  - name: Riviere-Pilote
    url: https://rivierepilote.fr
  - name: Riviere-Salee
    url: http://riviere-salee.fr
  - name: Saint-Pierre
    url: https://saintpierre-mq.fr
  - name: Les Anses d Arlet
    url: https://ville-ansesdarlet.fr
  - name: Trois-Ilets
    url: https://villedestroisilets.com
  - name: Le Carbet
    url: https://www.villeducarbet.fr
  - name: Le Lorrain
    url: https://villedulorrain.com
  - name: Le Francois
    url: https://www.ville-francois.fr
  - name: Le Robert
    url: https://www.ville-robert.fr
  - name: Sainte-Marie
    url: https://www.ville-saintemarie.fr
  - name: Case-Pilote
    url: https://mairiecasepilote.fr
  - name: Morne-Vert
    url: https://www.morne-vert.fr
  - name: Comite Martiniquais du tourisme
    url: https://www.martinique.org
  - name: Martinique Transport
    url: http://www.martiniquetransport.mq
  - name: Observatoire Eau Martinique
    url: https://www.observatoire-eau-martinique.fr
  - name: Odyssi
    url: https://www.odyssi.fr
  - name: cesecem
    url: https://www.cesecem.mq
  - name: Parc Naturel Regional de la Martinique
    url: http://pnr-martinique.com
  - name: Maison Martiniquaise des Personnes en situation d Handicap
    url: https://mdph972.fr
  - name: Association de Gestion de l Environnement de la Formation en Martinique
    url: https://www.agefma.mq
  - name: Tropiques Atrium
    url: https://tropiques-atrium.fr
  - name: Martinique Developpement
    url: https://www.martiniquedev.fr
  - name: Campus Caraibeen des Arts
    url: https://cca-martinique.com
  - name: Technopole Martinique
    url: https://www.technopolemartinique.org
  - name: Pole Agro-Ressource de Martinique
    url: https://parm.mq
  - name: Biodiversite Martinique
    url: http://www.biodiversite-martinique.fr
  - name: Initiative Martinique Active
    url: https://www.initiative-martinique.com
  - name: Institut Martiniquais du Sport
    url: https://www.ims.mq
  - name: ADIL Martinique
    url: https://www.adilmartinique.org
  - name: Institut Martiniquais de formation professionnelle pour adultes
    url: https://imfpa.mq
  - name: Hyppodrome de Carrere
    url: http://hippodromedecarrere.fr
  - name: Le Galion
    url: http://saem-legalion.net
  - name: Grande Baie Martinique
    url: https://grandebaiemartinique.com
  - name: Collecte dechets
    url: http://collecte-dechets.cacem.fr
  - name: Mission locale du centre de la Martinique
    url: https://www.milcem.com
  - name: Office du tourisme du centre de la Martinique
    url: https://tourisme-centre.fr
  - name: Préfecture de la Martinique
    url: https://www.martinique.gouv.fr
  - name: SMTVD
    url: https://www.smtvd.fr
  - name: zetwal
    url: https://www.zetwal.mq

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /martinique-public-websites
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Martinique public websites monitoring
  introTitle: "Monitor Martinique's public websites"
  introMessage: Based on **[upptime](https://github.com/upptime/upptime)**. Contribute on the public github repository [martinique-public-websites](https://github.com/glefait/martinique-public-websites).
  navbar:
    - title: Status
      href: /martinique-public-websites
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
